language: generic

branches:
  only:
    - travis

dist: xenial

addons:
  apt:
    update: true
    sources:
      - sourceline: 'deb http://us.archive.ubuntu.com/ubuntu/ xenial universe'
    packages:
      - scons
      - doxygen
      - graphviz
      - python-sphinx
      - python-breathe

script:
  - git clone https://github.com/roc-streaming/roc-toolkit.git
  - scons -C roc-toolkit docs
  - cp -a roc-toolkit/html www/toolkit

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  target_branch: master
  skip_cleanup: true
  local_dir: www
  on:
    branch: travis
