name: build

on:
  push:
    branches:
      - source
  repository_dispatch:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout www
        uses: actions/checkout@v4

      - name: Checkout roc-toolkit
        uses: actions/checkout@v4
        with:
          repository: roc-streaming/roc-toolkit
          path: roc-toolkit

      - name: Checkout rocd
        uses: actions/checkout@v4
        with:
          repository: roc-streaming/rocd
          path: rocd

      - name: Build roc-toolkit documentation
        run: |
          ./roc-toolkit/scripts/make_doc.sh
          cp -av roc-toolkit/docs/html www/toolkit

      - name: Build rocd documentation
        run: |
          cp -av rocd/docs www/daemon

      - name: Publish web-site
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: content
          folder: www
          single-commit: true
