name: build

on:
  push:
    branches:
      - source
  repository_dispatch:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get -y install scons doxygen graphviz

      - name: Install sphinx
        run: |
          sudo pip3 install Sphinx==5.3.0
          sudo pip3 install breathe==4.34.0

      - name: Build documentation
        run: |
          git clone https://github.com/roc-streaming/roc-toolkit.git
          scons -C roc-toolkit --enable-sphinx --enable-doxygen docs
          cp -av roc-toolkit/docs/html www/toolkit

      - name: Publish web-site
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: content
          folder: www
          single-commit: true
