name: build

on:
  push:
    branches:
      - source
  repository_dispatch:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout www
        uses: actions/checkout@v4

      - name: Checkout roc-toolkit
        uses: actions/checkout@v4
        with:
          repository: roc-streaming/roc-toolkit
          path: roc-toolkit

      - name: Checkout rocd
        uses: actions/checkout@v4
        with:
          repository: roc-streaming/rocd
          path: rocd

      - name: Build roc-toolkit documentation
        run: |
          docker run --rm -t -u "${UID}" -v "$(pwd)":/opt/roc -w /opt/roc rocstreaming/env-sphinx \
              scons -C roc-toolkit --enable-sphinx --enable-doxygen docs
          cp -av roc-toolkit/docs/html www/toolkit

      - name: Build rocd documentation
        run: |
          make -C rocd html
          cp -av rocd/docs/html www/daemon

      - name: Publish web-site
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: content
          folder: www
          single-commit: true
